### ISSUE TITLE
[Android]ScrollableTabBar Crash

### ISSUE THREAD

**Issue by Richard-Cao** [skv-headless/react-native-scrollable-tab-view#328]
```
java.lang.AssertionError: availableWidth is indefinite so widthMeasureMode must be CSSMeasureMode.UNDEFINED
                                                               at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:65)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:502)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:938)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:706)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:938)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:938)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:938)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:938)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1304)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1088)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1304)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1088)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1088)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1088)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1304)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1304)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:373)
                                                               at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:251)
                                                               at com.facebook.csslayout.CSSNode.calculateLayout(CSSNode.java:144)
                                                               at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:731)
                                                               at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:505)
                                                               at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:494)
                                                               at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:457)
                                                               at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:137)
                                                               at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.onBatchComplete(CatalystInstanceImpl.java:453)
                                                               at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
                                                               at java.lang.Thread.run(Thread.java:818)
```

Only on Android.

**Comment by skv-headless** [comment]
How can I reproduce it?

**Comment by Richard-Cao** [comment]
@skv-headless https://github.com/attentiveness/reading/blob/master/app/pages/Main.js#L340, change `DefaultTabBar` to `ScrollableTabBar ` can reproduce . only on android

**Comment by hdjjun** [comment]
My app crashed too.Just replace DefaultTabBar with ScrollableTabBar.

**Comment by skv-headless** [comment]
If you reproduce this on examples I'll take a look as soon as possible

**Comment by sunquanzhi** [comment]
ScrollableTabBar crash for android, DefaultTabBar work well.

**Comment by Richard-Cao** [comment]
@sunquanzhi yes

**Comment by legendtang** [comment]
Same problem as described above.

**Comment by Richard-Cao** [comment]
Still crash……

**Comment by Richard-Cao** [comment]
@skv-headless Anything else?

**Comment by Richard-Cao** [comment]
Dynamic tabs use ScrollableTabBar……  @skv-headless

**Comment by aqnaruto** [comment]
@Richard-Cao 那咋办，现在还崩溃么。蛋疼。

**Comment by aqnaruto** [comment]
我试了，0.21版本的 是怎么弄都不会蹦的。后面react升级了 ，就出现蹦了。主要是语法经常变  很坑爹，估计里面的逻辑都乱掉了把。 @Richard-Cao

**Comment by Richard-Cao** [comment]
@aqnaruto Still crash.

**Comment by aqnaruto** [comment]
你说的这个是启动的时候蹦，还是使用这个的时候才会蹦 @Richard-Cao

**Comment by Richard-Cao** [comment]
@aqnaruto Crash when use this.

**Comment by aqnaruto** [comment]
@Richard-Cao 非常感谢。但是我在另一个oscgit的项目上 react native 0.21的版本 是很流畅的用不会崩溃的。后来我升级到0.32版本了直接启动不了。我也是累觉不爱。对了 下了您只做的ireading ，也是启动不了说
![image](https://cloud.githubusercontent.com/assets/9067159/18380153/9c3a688c-76a8-11e6-85a2-1c078c4a6778.png)是那个项目只有ios版本没有 安卓版本吗 我看了安卓上好像没写什么东西

**Comment by haomiaozhichen** [comment]
@skv-headless 我也发现这个问题了，ireading项目（地址：https://github.com/attentiveness/reading），把代码下载下来，安装好包依赖，react-native run-android后，出现如楼上aqnaruto的图片中的错误

**Comment by Richard-Cao** [comment]
@haomiaozhichen Please speak English……

**Comment by skv-headless** [comment]
Please try version from master. There is no ViewPager. I appreciate any feedback.

**Comment by Richard-Cao** [comment]
still crash in 0.7.0.

**Comment by cbilgili** [comment]
+1 I have same problem.

**Comment by cinder92** [comment]
still crash...
