### ISSUE TITLE
Enzyme tests with Mocha fails 

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [skv-headless/react-native-scrollable-tab-view#444]
I have a `redux` application. And I use [enzyme](https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md) to test my components and containers. Mocha is my test runner

When I run `mocha --require react-native-mock/mock --compilers js:babel-register --recursive`, am seeing below errors

```
node_modules/react-native-scrollable-tab-view/index.js:107
      return <DefaultTabBar {...props} />;
             ^
SyntaxError: Unexpected token <
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Module._extensions..js (module.js:565:10)
```

Am no JS expert and so unable to help with a PR at this point. But any help in fixing the above will be greatly appreciated.

**Comment by sathyakumarseshachalam** [comment]
I used mockery to substitute a mock Component to make the tests pass.
